
name: 'test eslam'
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: [self-hosted]

    steps:
    - uses: 'actions/checkout@v1'

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      env:
        region: eu-west-1
      

