
name: 'test eslam'
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: [self-hosted]

    steps:
    - uses: 'actions/checkout@v1'

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      
    - name: 'Test2'
      uses: docker://604664627747.dkr.ecr.eu-west-1.amazonaws.com/dbz_kube_gitlab_runner:v1.4.0
      with:
        entrypoint: kubectl
        args: version
