
name: 'test eslam'
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: [self-hosted]

    steps:
    - uses: 'actions/checkout@v1'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: eu-west-1
        

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      env:
        region: eu-west-1

    - name: Pull from Amazon ECR
      run: |
        docker pull 604664627747.dkr.ecr.eu-west-1.amazonaws.com/dbz_kube_gitlab_runner:v1.4.0

